# -*- coding: utf-8 -*-
"""MLCT1.ipynb

Automatically generated by Colab. Test

Original file is located at
    https://colab.research.google.com/drive/1n-0lzU5NrRWHOH39ztsysltat8SkeAIv

Importing the required libraries
"""

import pandas as pd

"""Loading the dataset from github into a dataframe"""

url = "https://raw.githubusercontent.com/anmol-master/isb-the-overfitters/refs/heads/main/MLCT1/Kaggle%20Song%20Input%20Data/song_data.csv"
df = pd.read_csv(url , on_bad_lines='skip')

df